<a href="https://colab.research.google.com/github/nitkum41/Machine-Learning/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [3]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

In [4]:

dataset = pd.read_excel("Folds5x2_pp.xlsx")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [6]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=.2,random_state=0)

### Splitting the dataset into the Training set and Test set

## Part 2 - Building the ANN

### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [9]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [11]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN model on the Training set

In [12]:
ann.fit(x_train,y_train, batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 86803.2530
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 364.4449
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 348.3566
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 329.3282
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 299.5209
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 277.3061
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 245.8358
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 219.8019
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 195.8185
Epoch 10/100
240/240 [==============================] - 0s 997us/step - loss: 169.1519
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 147.7374
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - 

### Predicting the results of the Test set

In [13]:
y_pred=ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis=1))

[[432.48 431.23]
 [463.45 460.01]
 [466.94 461.14]
 ...
 [474.16 473.26]
 [440.97 438.  ]
 [460.15 463.28]]
